### PR TITLE
Allow to setup app with multiple db configrations

### PR DESCRIPTION
**Pull request by artofhuman**
Allow to setup app with multiple DB configurations  …
Combustion recreates all databases in the database.yml config.
It PR also add ability to run test for different providers in docker:
- sqlite
- postgresql
- mysql

For run tests in docker just run `make`

U can see build log here: https://travis-ci.org/artofhuman/combustion/builds/164398228

### CODE REVIEW

**Comment by artofhuman** [comment]
@pat /cc

**Comment by artofhuman** [comment]
@pat Can u take a look?

**Comment by pat** [comment]
Hi @artofhuman - I haven't forgotten about this, it's just that the tail end of the year has been particularly busy. Hoping to have a proper look next week when I'm on a break.

**Comment by pat** [comment]
Hi Semyon - just reviewing this now (finally!). I'm happy for Combustion to handle multiple databases, so merging that part in sounds good. However, what's the purpose of adding Docker in? Is there a need for this?

**Comment by artofhuman** [comment]
@pat Thanks for the review 🎄 . About docker, I add docker for simplifying testing. For example, if a developer has not all databases installed on his machine. Also, docker allows run tests in Travis in few lines config. 
If you do not want docker in this repo we can remove that anyway.

**Comment by pat** [comment]
It's certainly a nice idea of having Docker, I just feel it's not necessary, and I'd prefer to keep things simpler. So, if you could alter the pull request to be just the database changes, that'd be great :)

**Comment by artofhuman** [comment]
I remove docker and change travis config, last build https://travis-ci.org/artofhuman/combustion/builds/188466722

**Comment by pat** [comment]
Great, thank you! Just merged it in :)

**Comment by artofhuman** [comment]
thanks 👍

**Pull request merged**
