### PR TITLE
Fix ActiveRecord::DuplicateMigrationVersionError error

### PR DESCRIPTION
**Pull request by artofhuman**
ActiveRecord::DuplicateMigrationVersionError occurs when engine initializer
add migrations like this:
``` ruby
class Engine < ::Rails::Engine
  initializer :same_initializer do |app|
    app.config.paths['db/migrate'].concat(config.paths['db/migrate'].expanded)
  end
end

### CODE REVIEW

**Comment by bibendi** [comment]
:up:

**Comment by bibendi** [comment]
@pat Do you maintain this repo?

**Comment by pat** [comment]
I do, and I'm well aware I'm much behind with some pull requests…

My concern is that Combustion is ideally built to work with Rails 3.2 onwards, but there are no tests. Writing tests for a testing library and getting them to work across Rails versions is painful - but currently I wonder whether each pull request is catering to behaviour in specific Rails versions, and I just don't know. I've not made the time to write a testing harness or *something* that would make me more certain, but that's the path I'd like to get things along eventually.

I guess a starting point is: what versions of Rails has this pull request been tested against? :)

**Comment by artofhuman** [comment]
@pat we tested rails 3.1 3.2 and 4.0
I think i can create 2 gems to reproduce this problem

**Comment by artofhuman** [comment]
@pat, i add test case, look plz

**Comment by pat** [comment]
Fantastic, thanks! Just merged it in :D

**Comment by artofhuman** [comment]
@pat thanks

**Pull request merged**
